import {
  AlignLeft,
  AlignJustify,
  Hash,
  ListChecks,
  CheckSquare,
  ChevronDown,
  Calendar,
  Mail,
  Phone,
  Globe,
  Star,
  Clock,
  SlidersHorizontal,
  SectionIcon as Section,
  Image,
} from "lucide-react"

export const formElementTypes = [
  {
    value: "short-answer",
    label: "Short Answer",
    description: "A single line of text",
    icon: <AlignLeft className="h-4 w-4" />,
    category: "text",
  },
  {
    value: "paragraph",
    label: "Paragraph",
    description: "Multiple lines of text",
    icon: <AlignJustify className="h-4 w-4" />,
    category: "text",
  },
  {
    value: "number",
    label: "Number",
    description: "Numerical input",
    icon: <Hash className="h-4 w-4" />,
    category: "text",
  },
  {
    value: "multiple-choice",
    label: "Multiple Choice",
    description: "Select one option",
    icon: <ListChecks className="h-4 w-4" />,
    category: "choice",
  },
  {
    value: "checkboxes",
    label: "Checkboxes",
    description: "Select multiple options",
    icon: <CheckSquare className="h-4 w-4" />,
    category: "choice",
  },
  {
    value: "dropdown",
    label: "Dropdown",
    description: "Select from a list",
    icon: <ChevronDown className="h-4 w-4" />,
    category: "choice",
  },
  {
    value: "image-selection",
    label: "Image Selection",
    description: "Choose from images",
    icon: <Image className="h-4 w-4" />,
    category: "choice",
  },
  {
    value: "date",
    label: "Date",
    description: "Date picker",
    icon: <Calendar className="h-4 w-4" />,
    category: "special",
  },
  {
    value: "email",
    label: "Email",
    description: "Email address",
    icon: <Mail className="h-4 w-4" />,
    category: "special",
  },
  {
    value: "phone-number",
    label: "Phone Number",
    description: "Phone number input",
    icon: <Phone className="h-4 w-4" />,
    category: "special",
  },
  {
    value: "website-url",
    label: "Website URL",
    description: "URL input",
    icon: <Globe className="h-4 w-4" />,
    category: "special",
  },
  {
    value: "rating-scale",
    label: "Rating Scale",
    description: "Numerical rating",
    icon: <Star className="h-4 w-4" />,
    category: "scale",
  },
  {
    value: "time",
    label: "Time",
    description: "Time picker",
    icon: <Clock className="h-4 w-4" />,
    category: "scale",
  },
  {
    value: "range-slider",
    label: "Range Slider",
    description: "Slider for a range",
    icon: <SlidersHorizontal className="h-4 w-4" />,
    category: "scale",
  },
  {
    value: "section",
    label: "Section",
    description: "Section divider",
    icon: <Section className="h-4 w-4" />,
    category: "special",
  },
]

